### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by jenhausu** [attias/AADatePicker#2]
I can't build the project. Here is the error log I got.

```
clang: error: no such file or directory: '/Users/sokengou1/Downloads/AADatePicker-master/CustomDatePicker/CustomDatePicker-Prefix.pch'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

I still looking for a solution.

**Comment by bwash70** [comment]
You'll need to provide the code mate or we can't help you.

**Comment by jenhausu** [comment]
@bwash70 I didn't change anything. I just run the project then fail.
btw. What is code mate?

**Comment by jenhausu** [comment]
#### Solution!

go to Targets > Build Setting > Apple LLVM 6.0 - Language > Prefix Header
Change CustomDatePicker/CustomDatePicker-Prefix.pch into CustomDatePicker/AACustomDatePicker-Prefix.pch
The original path missed the `AA` word.
